# Generated by Django 5.2.6 on 2025-09-24 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('source', models.CharField(max_length=20)),
                ('source_url', models.URLField(default='')),
                ('published_at', models.DateTimeField()),
                ('bucket', models.CharField(default='mi-vid-transcription', max_length=255)),
                ('gcs_object', models.CharField(blank=True, max_length=1024, null=True)),
                ('sts_job_name', models.CharField(blank=True, max_length=512, null=True)),
                ('vi_operation_name', models.CharField(blank=True, max_length=512, null=True)),
                ('status', models.CharField(choices=[('NEW', 'Discovered'), ('TRANSFERRING', 'Transferring to GCS'), ('TRANSFER_FAILED', 'Transfer failed'), ('TRANSFER_DONE', 'Transfer complete'), ('TRANSCRIBING', 'Transcribing'), ('TRANSCRIBE_FAILED', 'Transcription failed'), ('COMPLETE', 'Complete')], default='NEW', max_length=32)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('transcript_text', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
