# Generated by Django 5.2.6 on 2025-09-21 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='audio_file_path',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='video',
            name='cleaned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='video',
            name='local_path',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(default='', max_length=255),
        ),
    ]
