# Generated by Django 5.2.6 on 2025-09-24 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='player_url',
            field=models.URLField(default=''),
        ),
    ]
