# Generated by Django 5.2.6 on 2025-09-22 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_video_audio_file_path_video_cleaned_video_local_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='file_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
