# Generated by Django 5.2.6 on 2025-09-22 20:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_video_file_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='url',
            new_name='source_url',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='transcript',
            new_name='transcript_text',
        ),
        migrations.RemoveField(
            model_name='video',
            name='audio_file_path',
        ),
        migrations.RemoveField(
            model_name='video',
            name='cleaned',
        ),
        migrations.RemoveField(
            model_name='video',
            name='downloaded',
        ),
        migrations.RemoveField(
            model_name='video',
            name='file_name',
        ),
        migrations.RemoveField(
            model_name='video',
            name='local_path',
        ),
        migrations.RemoveField(
            model_name='video',
            name='transcribed',
        ),
        migrations.AddField(
            model_name='video',
            name='bucket',
            field=models.CharField(default='mi-vid-transcription', max_length=255),
        ),
        migrations.AddField(
            model_name='video',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='gcs_object',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='published_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='video',
            name='status',
            field=models.CharField(choices=[('NEW', 'Discovered'), ('TRANSFERRING', 'Transferring to GCS'), ('TRANSFER_FAILED', 'Transfer failed'), ('TRANSFER_DONE', 'Transfer complete'), ('TRANSCRIBING', 'Transcribing'), ('TRANSCRIBE_FAILED', 'Transcription failed'), ('COMPLETE', 'Complete')], default='NEW', max_length=32),
        ),
        migrations.AddField(
            model_name='video',
            name='sts_job_name',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='video',
            name='vi_operation_name',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='source',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(max_length=500),
        ),
    ]
