version: "3.3"

services:
  django:
    build: ./backend
    container_name: dev-django
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8001:8000
    env_file:
      - ./.env.dev
    volumes:
      - ./backend/:/srv/app
      - static:/srv/app/static
      - media:/srv/app/media
    depends_on:
      - db
      - redis
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/srv/app/credentials/google-vid-int.json
  react:
    build: ./frontend
    container_name: dev-react
    command: npm start
    stdin_open: true
    ports:
      - 3001:3000
    env_file:
      - ./.env.dev
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    volumes:
      - ./frontend/:/srv/app
      - node_modules:/srv/app/node_modules
    depends_on:
      - django
  db:
    image: postgres:16.1-alpine
    container_name: dev-db
    ports:
      - 5432:5432
    env_file: ./.env.dev
    volumes:
      - postgres_data:/var/lib/postgresql/data
  nginx:
    build: ./nginx
    container_name: dev-nginx
    ports:
      - 8080:80
    restart: always
    volumes:
      - static:/srv/app/static
      - media:/srv/app/media
    depends_on:
      - django
      - react
      - db

  redis:
    image: redis:7
    container_name: dev-redis

  worker:
    build: ./backend
    container_name: dev-worker
    command: celery -A api worker -l INFO --concurrency=2
    env_file:
      - ./.env.dev
    volumes:
      - ./backend/:/srv/app
    depends_on:
      - django
      - redis
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/srv/app/credentials/google-vid-int.json
  beat:
    build: ./backend
    container_name: dev-beat
    command: celery -A api beat -l INFO
    env_file:
      - ./.env.dev
    volumes:
      - ./backend/:/srv/app
    depends_on:
      - django
      - redis
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/srv/app/credentials/google-vid-int.json

volumes:
  node_modules:
  postgres_data:
  media:
  static:
